"""Initial migration.

Revision ID: d0c7b8e4b57c
Revises: 
Create Date: 2022-11-08 17:00:02.151921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7247fe7be69f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('street_address', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant', sa.Integer(), nullable=True),
    sa.Column('user_name', sa.String(length=30), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('review_text', sa.String(length=500), nullable=True),
    sa.Column('review_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['restaurant'], ['restaurant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), primary_key=True),
    sa.Column('email', sa.String(200), unique=True, nullable=False ),
    sa.Column('password', sa.String(200), nullable=False),
    sa.Column('name', sa.String(200)),
    sa.Column('company', sa.String(200), unique=True, nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('certificates',
    sa.Column('id', sa.Integer(), nullable=False, primary_key=True),
    sa.Column('sender', sa.String(length=200), nullable=False),
    sa.Column('recipient', sa.String(length=200), nullable=False),
    sa.Column('po_number', sa.String(length=50), nullable=False),
    sa.Column('batch_number', sa.String(length=50), nullable=True),
    sa.Column('part_number', sa.String(length=50), nullable=True),
    sa.Column('assembly_number', sa.String(length=50), nullable=True),
    sa.Column('manufacturing_country', sa.String(length=50), nullable=True),
    sa.Column('reach_compliant', sa.Boolean(), nullable=True),
    sa.Column('hazardous', sa.Boolean(), nullable=True),
    sa.Column('material_expiry_date', sa.String(length=50), nullable=True),
    sa.Column('additional_notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review')
    op.drop_table('restaurant')
    op.drop_table('certificates')
    # ### end Alembic commands ###